#include <stdio.h>

/* Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89. By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms */

int main(void) {
    int next;
    int prev = 0;
    int curr = 1;
    int result = 0;

    while (curr <= 4000000 && next < 4000000) {
        next = prev + curr;
        if (next % 2 == 0) {
            result += next;
        }
        prev = curr;
        curr = next;
    }

    printf("Result: %d\n", result);

    return 0;
}
