# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function sum_even_fibs(n)
    even_sum = 2
    terms = [1, 2]
    while true
        new_term = terms[end] + terms[end-1]
        if new_term > n
            break
        end

        append!(terms, new_term)
        if new_term % 2 == 0
            even_sum += new_term
        end
    end

    return even_sum
end

println(sum_even_fibs(4_000_000))
