# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# It turns out every 3rd fib term is even
function sum_even_fibs(limit)
    a, b = 2, 8
    even_sum = 0

    while a <= limit
        even_sum += a
        a, b = b, 4b + a
    end

    return even_sum
end

println(sum_even_fibs(4_000_000))
